# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: disc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndisc.proto\x12\x04\x64isc\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n\x0clist_request\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\"\x18\n\x08uuidData\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"b\n\x04\x66ile\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12+\n\x07version\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x06\n\x04void\"\x17\n\x06result\x12\r\n\x05reply\x18\x01 \x01(\t\"4\n\x05write\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\t\"Z\n\rwriteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12+\n\x07version\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\" \n\x06Server\x12\x16\n\x0eserver_address\x18\x01 \x01(\t\"0\n\x0bServer_list\x12!\n\x0bserver_list\x18\x01 \x03(\x0b\x32\x0c.disc.Server2\xe8\x02\n\x16RegisterReplicaService\x12-\n\x0freplicaRegister\x12\x0c.disc.Server\x1a\x0c.disc.Server\x12/\n\x0egetReplicaList\x12\n.disc.void\x1a\x11.disc.Server_list\x12\x35\n\x0cregistryList\x12\x12.disc.list_request\x1a\x11.disc.Server_list\x12\x30\n\x0cwriteRequest\x12\x0b.disc.write\x1a\x13.disc.writeResponse\x12.\n\rupdatePrimary\x12\x11.disc.Server_list\x1a\n.disc.void\x12&\n\x08readFile\x12\x0e.disc.uuidData\x1a\n.disc.file\x12-\n\rdeleteRequest\x12\x0e.disc.uuidData\x1a\x0c.disc.resultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'disc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIST_REQUEST._serialized_start=53
  _LIST_REQUEST._serialized_end=95
  _UUIDDATA._serialized_start=97
  _UUIDDATA._serialized_end=121
  _FILE._serialized_start=123
  _FILE._serialized_end=221
  _VOID._serialized_start=223
  _VOID._serialized_end=229
  _RESULT._serialized_start=231
  _RESULT._serialized_end=254
  _WRITE._serialized_start=256
  _WRITE._serialized_end=308
  _WRITERESPONSE._serialized_start=310
  _WRITERESPONSE._serialized_end=400
  _SERVER._serialized_start=402
  _SERVER._serialized_end=434
  _SERVER_LIST._serialized_start=436
  _SERVER_LIST._serialized_end=484
  _REGISTERREPLICASERVICE._serialized_start=487
  _REGISTERREPLICASERVICE._serialized_end=847
# @@protoc_insertion_point(module_scope)
